/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Agent_dispatcher_unit: typeof import('./src/components/layout/agent_dispatcher_unit.vue')['default']
    AgentDetail: typeof import('./src/components/layout/agentDetail.vue')['default']
    AgentDispatcher: typeof import('./src/components/layout/agentDispatcher/agentDispatcher.vue')['default']
    AgentDispatcher_unit: typeof import('./src/components/layout/agentDispatcher/agentDispatcher_unit.vue')['default']
    AgentDispatchers: typeof import('./src/components/layout/agentDispatchers.vue')['default']
    AgentDispatchers_view: typeof import('./src/components/layout/agentDispatcher/agentDispatchers_view.vue')['default']
    AssistantsDrawer: typeof import('./src/components/layout/assistantsDrawer.vue')['default']
    Base_button: typeof import('./src/components/examples/base_button.vue')['default']
    Base_drawer: typeof import('./src/components/examples/base_drawer.vue')['default']
    Base_table: typeof import('./src/components/examples/base_table.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    Elements: typeof import('./src/components/examples/elements.vue')['default']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    HelloWorld: typeof import('./src/components/examples/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/common/icon.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Main: typeof import('./src/components/layout/main.vue')['default']
    NavMenu: typeof import('./src/components/layout/navMenu.vue')['default']
    NewTask: typeof import('./src/components/layout/newTask.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Template: typeof import('./src/components/examples/template.vue')['default']
  }
}
